DEBUG = True
SQLALCHEMY_ECHO = False
SQLALCHEMY_DATABASE_URI = "sqlite:///auth/auth.sqlite"
SQLALCHEMY_TRACK_MODIFICATIONS = True
SECRET_KEY = "d89abafebaf5a2cedbbeb0935fbe75dc"

THREADED = True
USE_RELOADER = False
VIDEO_DIR_MODE = True
VIDEO_SOURCE = "D:/VS/AVS/testv/test1.mp4"
VIDEO_SOURCE_DIR = "D:/VS/AVS/testv"
